### ISSUE TITLE
Missing module torch._higher_order_ops when running a simple `$ tune`

### ISSUE THREAD

**Issue by NotTheStallion** [pytorch/torchtune#1071]
I am trying to do multi-node fine-tuning on Llama3-7B and i just installed torchtune. I tried the command `$ tune ls` and it showed me this error `Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/tune", line 5, in <module>
    from torchtune._cli.tune import main
  File "/home/ubuntu/torchtune/torchtune/__init__.py", line 9, in <module>
    from torchtune import datasets, models, modules, utils
  File "/home/ubuntu/torchtune/torchtune/datasets/__init__.py", line 7, in <module>
    from torchtune.datasets._alpaca import alpaca_cleaned_dataset, alpaca_dataset
  File "/home/ubuntu/torchtune/torchtune/datasets/_alpaca.py", line 9, in <module>
    from torchtune.datasets._instruct import instruct_dataset, InstructDataset
  File "/home/ubuntu/torchtune/torchtune/datasets/_instruct.py", line 12, in <module>
    from torchtune.config._utils import _get_component_from_path
  File "/home/ubuntu/torchtune/torchtune/config/__init__.py", line 7, in <module>
    from ._instantiate import instantiate
  File "/home/ubuntu/torchtune/torchtune/config/_instantiate.py", line 12, in <module>
    from torchtune.config._utils import _get_component_from_path, _has_component
  File "/home/ubuntu/torchtune/torchtune/config/_utils.py", line 15, in <module>
    from torchtune.utils import get_logger, get_world_size_and_rank
  File "/home/ubuntu/torchtune/torchtune/utils/__init__.py", line 7, in <module>
    from ._checkpointing import (  # noqa
  File "/home/ubuntu/torchtune/torchtune/utils/_checkpointing/__init__.py", line 7, in <module>
    from ._checkpointer import (  # noqa
  File "/home/ubuntu/torchtune/torchtune/utils/_checkpointing/_checkpointer.py", line 18, in <module>
    from torchtune.models.mistral import (
  File "/home/ubuntu/torchtune/torchtune/models/mistral/__init__.py", line 7, in <module>
    from ._component_builders import lora_mistral, mistral, mistral_classifier
  File "/home/ubuntu/torchtune/torchtune/models/mistral/_component_builders.py", line 8, in <module>
    from torchtune.modules.common_utils import reparametrize_as_dtype_state_dict_post_hook
  File "/home/ubuntu/torchtune/torchtune/modules/__init__.py", line 8, in <module>
    from .common_utils import reparametrize_as_dtype_state_dict_post_hook
  File "/home/ubuntu/torchtune/torchtune/modules/common_utils.py", line 12, in <module>
    from torchao.dtypes.nf4tensor import NF4Tensor
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torchao/__init__.py", line 2, in <module>
    from .quantization.quant_api import apply_dynamic_quant
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torchao/quantization/__init__.py", line 7, in <module>
    from .smoothquant import *  # noqa: F403
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torchao/quantization/smoothquant.py", line 18, in <module>
    import torchao.quantization.quant_api as quant_api
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torchao/quantization/quant_api.py", line 22, in <module>
    from .dynamic_quant import DynamicallyPerAxisQuantizedLinear
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torchao/quantization/dynamic_quant.py", line 10, in <module>
    from .quant_primitives import (
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torchao/quantization/quant_primitives.py", line 9, in <module>
    from torch._higher_order_ops.out_dtype import out_dtype
ModuleNotFoundError: No module named 'torch._higher_order_ops'
`
I tried `$ tune` alone and it showed the same error. I tried to simply import torch._higher_order_ops and i got this 
`$ python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import torch._higher_order_ops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch._higher_order_ops'`. 

I am not sure of where the problem is, but if you have any idea of what to check i am all ears.

**Comment by SalmanMohammadi** [comment]
Hey @NotTheStallion. Thanks for raising this. There was a similar issue here https://github.com/pytorch/torchtune/issues/1038. Could you try ensure you have `torch==2.3.0, torchao==0.1, torchtune==0.1.1` installed?

**Comment by NotTheStallion** [comment]
That solved the problem, but sadly the torch version created other compatibility issues. 
Thank you for the help.
