### ISSUE TITLE
 Error when resuming wandb run with updated config file

### ISSUE THREAD

**Issue by parthsarthi03** [pytorch/torchtune#1080]
Hi, thanks for the great work! I am encountering an error when trying to resume a wandb run after making changes to my config file. Even after passing `allow_val_change: True` to the config file, the issue remains.

```console
wandb: ERROR Attempted to change value of key "tokenizer"
wandb: ERROR If you really want to do this, pass allow_val_change=True to config.update()
Traceback (most recent call last):
  File "/home/ps/torchtune/recipes/full_finetune_distributed.py", line 576, in <module>
    sys.exit(recipe_main())
             ^^^^^^^^^^^^^
  File "/home/ps/torchtune/torchtune/config/_parse.py", line 50, in wrapper
    sys.exit(recipe_main(conf))
             ^^^^^^^^^^^^^^^^^
  File "/home/ps/torchtune/recipes/full_finetune_distributed.py", line 570, in recipe_main
    recipe.setup(cfg=cfg)
  File "/home/ps/torchtune/recipes/full_finetune_distributed.py", line 178, in setup
    self._metric_logger.log_config(cfg)
  File "/home/ps/torchtune/torchtune/utils/metric_logging.py", line 219, in log_config
    self._wandb.config.update(resolved)#, allow_val_change=self.config_allow_val_change)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/ps_l3/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 184, in update
    sanitized = self._update(d, allow_val_change)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/ps_l3/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 177, in _update
    sanitized = self._sanitize_dict(
                ^^^^^^^^^^^^^^^^^^^^
  File "/home/ps/miniconda3/envs/ps_l3/lib/python3.12/site-packages/wandb/sdk/wandb_config.py", line 264, in _sanitize_dict
    k, v = self._sanitize(k, v, allow_val_change)
```

```yaml
metric_logger:
  _component_: torchtune.utils.metric_logging.WandBLogger
  log_dir: /data/ps/l3/logs/
  project: llama_3
  resume: True 
  id: abcdef
  allow_val_change: True
```

**Comment by parthsarthi03** [comment]
fixed by #1081.
