### ISSUE TITLE
ImportError: cannot import name 'packaging' from 'pkg_resources'

### ISSUE THREAD

**Issue by JadarTheObscurity** [pytorch/torchtune#1111]
### Environment:
- Ubuntu 24.04
- Python 3.12.3
- setuptools 70.1.0

### Problem:
Running `tune` throws the following error
```
Traceback (most recent call last):                                                                                                                                                                                  File "/home/ubuntu/llama3/venv/bin/tune", line 5, in <module>                                                                                                                                                       from torchtune._cli.tune import main                                                                                                                                                                            File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/__init__.py", line 9, in <module>                                                                                                             from torchtune import datasets, models, modules, utils                                                                                                                                                          File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/datasets/__init__.py", line 7, in <module>
    from torchtune.datasets._alpaca import alpaca_cleaned_dataset, alpaca_dataset
  File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/datasets/_alpaca.py", line 10, in <module>
    from torchtune.datasets._instruct import InstructDataset
  File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/datasets/_instruct.py", line 12, in <module>
    from torchtune.config._utils import _get_instruct_template
  File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/config/__init__.py", line 7, in <module>
    from ._instantiate import instantiate
  File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/config/_instantiate.py", line 12, in <module>
    from torchtune.config._utils import _get_component_from_path, _has_component
  File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/config/_utils.py", line 16, in <module>
    from torchtune.utils import get_logger, get_world_size_and_rank
  File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/utils/__init__.py", line 49, in <module>
    from .precision import (
  File "/home/ubuntu/llama3/venv/lib/python3.12/site-packages/torchtune/utils/precision.py", line 21, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/ubuntu/llama3/venv/lib/python3.12/site-packages/pkg_resources/__init__.py)
```

### Solution
Switch to setuptools==69.0.0 solves the problem

**Comment by ebsmothers** [comment]
Hi @JadarTheObscurity, thanks for pointing this out. There's an issue on the setuptools repo about this, seems they did not notify about breaking backwards compatibility on this API in version 70.0 because it's not officially a public API (though it is quite widely used). Anyways, I've opened #1114 to pin to an older version in our default install.

**Comment by ebsmothers** [comment]
Actually sorry @JadarTheObscurity I didn't look closely enough here. I think you are running on an older version of the repo, we no longer have this import as of #803. Can you update to the latest nightly instead? I am gonna close the PR

**Comment by JadarTheObscurity** [comment]
Yes, the latest nightly works without using setuptools. Thanks!
