### ISSUE TITLE
Nsys Profiling error for distributed training of LLaMA 2 7B

### ISSUE THREAD

**Issue by shamweelm** [pytorch/torchtune#1199]
I am currently trying to profile a distributed training for a LLAMA 2 7B model using 3xA6000 (48*3 GB) GPUs.

When I run the below command, the training runs without any issues:
```
tune run --nnodes 1 --nproc_per_node 3 full_finetune_distributed --config llama2/7B_full
```

However, when I run a profiling with NSYS, I get the following error:
```
nsys profile -t nvtx,cuda,osrt,cudnn,cublas,mpi --sample=cpu --stats=true --cudabacktrace=all --force-overwrite=true --python-sampling-frequency=1000 --python-sampling=true --cuda-memory-usage=true --python-backtrace=cuda --gpuctxsw=true --show-output=true --export=sqlite -o /home/logs/dlprof_training_profile_llama_july19/dlprof_training_1_bsz/nsys_profile tune run --nnodes 1 --nproc_per_node 3 full_finetune_distributed --config llama2/7B_full
```

Error:
```
 INFO:torchtune.utils.logging:Model is wrapped with FSDP at : 2024-07-19 01:27:17.021160
INFO:torchtune.utils.logging:Optimizer is initialized.
INFO:torchtune.utils.logging:Dataset and Sampler are initialized.
  0%|                                                                            | 0/8667 [00:00<?, ?it/s]W0719 01:27:30.704000 140471808695552 torch/distributed/elastic/multiprocessing/api.py:851] Sending process 3648 closing signal SIGTERM
E0719 01:27:33.682000 140471808695552 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -11) local_rank: 0 (pid: 3646) of binary: /root/miniconda3/envs/torchtune/bin/python
Running with torchrun...
Traceback (most recent call last):
  File "/root/miniconda3/envs/torchtune/bin/tune", line 8, in <module>
    sys.exit(main())
  File "/home/research/torchtune/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/research/torchtune/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/research/torchtune/torchtune/_cli/run.py", line 177, in _run_cmd
    self._run_distributed(args)
  File "/home/research/torchtune/torchtune/_cli/run.py", line 88, in _run_distributed
    run(args)
  File "/root/miniconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/root/miniconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/research/torchtune/recipes/full_finetune_distributed.py FAILED
------------------------------------------------------------
```

**Comment by pbontrager** [comment]
I don’t have too much experience with NSight systems, could you confirm that the issue isn’t connected to torchrun? If you replace tune run with torchrun and the recipe with a dummy PyTorch script, does everything work correctly?

**Comment by shamweelm** [comment]
I did try with torchrun, the training runs without any issues. I have done some debugging when running with NSYS, 
```
optimizer.step()
```
causes a SEGV error.

```
free(): corrupted unsorted chunks
E0720 16:36:09.505000 139820868859712 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: -11) local_rank: 0 (pid: 3551) of binary: /root/miniconda3/envs/torchtune/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/torchtune/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/root/miniconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/root/miniconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/torchtune/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
recipes/full_finetune_distributed.py FAILED
------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-20_16:36:09
  host      : 3ba4ddcbcaf7
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 3552)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 3552
[2]:
  time      : 2024-07-20_16:36:09
  host      : 3ba4ddcbcaf7
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 3553)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 3553
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-20_16:36:09
  host      : 3ba4ddcbcaf7
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 3551)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 3551
======================================================
```

**Comment by pbontrager** [comment]
Could you cross post this issue on the nvidia developer forums? It seems there was an issue with DDP + NCCL a little over a year ago but that's [resolved](https://github.com/pytorch/pytorch/issues/94393). And there have been other user issues with seg faults (see [here](https://forums.developer.nvidia.com/t/segfaults-during-deep-learning-profiling-bug/273984/6)) that they have helped with. I don't believe the recipe you shared is doing anything too exotic from any standard pytorch script; it's an fsdp wrapped transformer using AdamW and activation checkpointing.

Something you could also try would be to run `tune run --nnodes 1 --nproc_per_node 3 lora_finetune_fsdp2 --config llama2/7B_lora`. I know you aren't trying to use LoRA, but we've currently only added FSDP2 to LoRA and you could test if the issue you're running into is related to FSDP.

**Comment by YI-MAX-YAN** [comment]
@shamweelm have you resolve this problem?
