### ISSUE TITLE
text_completion_dataset: RuntimeError: each element in list of batch should be of equal size

### ISSUE THREAD

**Issue by loretoparisi** [pytorch/torchtune#1394]
I have created an unstructured dataset using the `text_completion_dataset`:

```python
dataset = text_completion_dataset(
        tokenizer,
        source="text",
        column="text",
        data_files="t8.shakespeare.txt",
        split="train",
        max_seq_len=seq_length,
        packed=False
    )
    return dataset
```

using the text file [t8.shakespeare.txt](https://ocw.mit.edu/ans7870/6/6.006/s08/lecturenotes/files/t8.shakespeare.txt)

When I load it into a DataLoader with a `batch_size` > 1

```python
dataloader = torch.utils.data.DataLoader(dataset, batch_size=8, num_workers=0, shuffle=False)
 ```

I get the error

```
Traceback (most recent call last):
  File "dataset.py", line 77, in <module>
    for batch in dataloader:
  File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 673, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
    return self.collate_fn(data)
  File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 317, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 155, in collate
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 155, in <dictcomp>
    clone.update({key: collate([d[key] for d in batch], collate_fn_map=collate_fn_map) for key in elem})
  File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 170, in collate
    raise RuntimeError('each element in list of batch should be of equal size')
RuntimeError: each element in list of batch should be of equal size
```

I supposed that using `max_seq_len` was truncating all the tokens to `max_seq_len`, while it seems that padding is missing.

I have then tried to use `collate_fn`:

```python
dataloader = torch.utils.data.DataLoader(dataset, batch_size=8, num_workers=0, shuffle=False, collate_fn=lambda x: x)
print(dataloader)
    for batch in dataloader:
        for sample in batch:
            print(sample)
            print( len(sample['tokens']), tokenizer.decode(sample['tokens']) )
            
        break
```

this is the output
```
{'tokens': [128000, 2028, 374, 279, 220, 1041, 339, 469, 1342, 1052, 10666, 555, 5907, 52686, 11, 323, 128001], 'labels': [128000, 2028, 374, 279, 220, 1041, 339, 469, 1342, 1052, 10666, 555, 5907, 52686, 11, 323, 128001]}
17 This is the 100th Etext file presented by Project Gutenberg, and
{'tokens': [128000, 285, 10666, 304, 23915, 449, 4435, 11896, 11, 4953, 2637, 505, 872, 128001], 'labels': [128000, 285, 10666, 304, 23915, 449, 4435, 11896, 11, 4953, 2637, 505, 872, 128001]}
14 is presented in cooperation with World Library, Inc., from their
{'tokens': [128000, 17344, 315, 279, 12781, 323, 42482, 11325, 3442, 50, 13, 220, 5907, 52686, 128001], 'labels': [128000, 17344, 315, 279, 12781, 323, 42482, 11325, 3442, 50, 13, 220, 5907, 52686, 128001]}
15 Library of the Future and Shakespeare CDROMS.  Project Gutenberg
{'tokens': [128000, 61917, 19786, 469, 87042, 430, 527, 4276, 9277, 304, 279, 3142, 21749, 3001, 128001], 'labels': [128000, 61917, 19786, 469, 87042, 430, 527, 4276, 9277, 304, 279, 3142, 21749, 3001, 128001]}
15 often releases Etexts that are NOT placed in the Public Domain!!
{'tokens': [], 'labels': []}
0 
{'tokens': [128000, 2059, 37971, 128001], 'labels': [128000, 2059, 37971, 128001]}
4 Shakespeare
{'tokens': [], 'labels': []}
0 
{'tokens': [128000, 9, 2028, 469, 1342, 706, 3738, 7065, 25127, 499, 1288, 1373, 69322, 128001], 'labels': [128000, 9, 2028, 469, 1342, 706, 3738, 7065, 25127, 499, 1288, 1373, 69322, 128001]}
14 *This Etext has certain copyright implications you should read!*
```

While I do not get *here* the error anymore, the dataset samples have different sizes, so when loading in a real training it will not work.

**Comment by SalmanMohammadi** [comment]
Hey @loretoparisi. I think you might find our built-in collate function useful, which can be used across our datasets when loading them into a dataloder. Check out https://pytorch.org/torchtune/main/generated/torchtune.utils.padded_collate.html#torchtune.utils.padded_collate
```python
dataloader = torch.utils.data.DataLoader(dataset, batch_size=8, num_workers=0, shuffle=False, collate_fn=torchtune.utils.padded_collate)
```

**Comment by SalmanMohammadi** [comment]
You can also see how it's used in our training recipes [here](https://github.com/pytorch/torchtune/blob/f9f75bb563ecae371492a9d49da4a9f514c081b3/recipes/full_finetune_single_device.py#L435).

**Comment by loretoparisi** [comment]
@SalmanMohammadi thanks! I have added it

```python
from torchtune.utils import padded_collate
dataloader = torch.utils.data.DataLoader(dataset, batch_size=8, num_workers=0, shuffle=False, collate_fn=padded_collate)
print(dataloader)
 for sample in dataloader:
        print(sample)
        print( len(sample['tokens']), tokenizer.decode(sample['tokens']) )
        break
```

but now when running `tokenizer.decode` I'm getting

```
Traceback (most recent call last):
  File "dataset.py", line 100, in <module>
    print( len(sample['tokens']), tokenizer.decode(sample['tokens']) )
  File "/home/coder/.local/lib/python3.8/site-packages/torchtune/models/llama3/_tokenizer.py", line 126, in decode
    return self.tt_model.decode(token_ids, truncate_at_eos=truncate_at_eos)
  File "/home/coder/.local/lib/python3.8/site-packages/torchtune/modules/tokenizers/_tiktoken.py", line 151, in decode
    k = token_ids.index(self.eos_id)
AttributeError: 'Tensor' object has no attribute 'index'
```

for the sample

```
<torch.utils.data.dataloader.DataLoader object at 0x7f314db98e50>
{'tokens': tensor([[128000,   2028,    374,    279,    220,   1041,    339,    469,   1342,
           1052,  10666,    555,   5907,  52686,     11,    323, 128001],
        [128000,    285,  10666,    304,  23915,    449,   4435,  11896,     11,
           4953,   2637,    505,    872, 128001,      0,      0,      0],
        [128000,  17344,    315,    279,  12781,    323,  42482,  11325,   3442,
             50,     13,    220,   5907,  52686, 128001,      0,      0],
        [128000,  61917,  19786,    469,  87042,    430,    527,   4276,   9277,
            304,    279,   3142,  21749,   3001, 128001,      0,      0],
        [     0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0],
        [128000,   2059,  37971, 128001,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0],
        [     0,      0,      0,      0,      0,      0,      0,      0,      0,
              0,      0,      0,      0,      0,      0,      0,      0],
        [128000,      9,   2028,    469,   1342,    706,   3738,   7065,  25127,
            499,   1288,   1373,  69322, 128001,      0,      0,      0]]), 'labels': tensor([[128000,   2028,    374,    279,    220,   1041,    339,    469,   1342,
           1052,  10666,    555,   5907,  52686,     11,    323, 128001],
        [128000,    285,  10666,    304,  23915,    449,   4435,  11896,     11,
           4953,   2637,    505,    872, 128001,   -100,   -100,   -100],
        [128000,  17344,    315,    279,  12781,    323,  42482,  11325,   3442,
             50,     13,    220,   5907,  52686, 128001,   -100,   -100],
        [128000,  61917,  19786,    469,  87042,    430,    527,   4276,   9277,
            304,    279,   3142,  21749,   3001, 128001,   -100,   -100],
        [  -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100],
        [128000,   2059,  37971, 128001,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100],
        [  -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100,
           -100,   -100,   -100,   -100,   -100,   -100,   -100,   -100],
        [128000,      9,   2028,    469,   1342,    706,   3738,   7065,  25127,
            499,   1288,   1373,  69322, 128001,   -100,   -100,   -100]])}
```

**Comment by SalmanMohammadi** [comment]
So our tokenizers have the signature `def decode(self, ids: List[int]) -> str` - they take a list of integers and decode to a string. This means you need to call `.tolist()` on a tensor before decoding.
In your example, since you have a batch of tensors, try:
```python
# loop through every batch element
for i in range(sample["tokens"].shape[0]):
    print(len(sample["tokens"][i], tokenizer.decode(sample["tokens"][i].tolist()))
```

disclaimer: code may not work on first try. hope you get the gist  : )

**Comment by RdoubleA** [comment]
@loretoparisi This is expected, after collating the list of token ids becomes a Tensor, so you'll have to return to list form to decode properly:
```
print( len(sample['tokens']), tokenizer.decode(sample['tokens'].tolist()) )
```

**Comment by RdoubleA** [comment]
It may be good to also remove any empty lines so you don't waste samples that are entirely padding. This brings up a good point about no ability to apply a filter through `text_completion_dataset`... will create an issue

**Comment by loretoparisi** [comment]
@RdoubleA great thanks I works!

```
batch_size: 8
sample_size: 17
This is the 100th Etext file presented by Project Gutenberg, and
sample_size: 17
is presented in cooperation with World Library, Inc., from their
sample_size: 17
Library of the Future and Shakespeare CDROMS.  Project Gutenberg
sample_size: 17
often releases Etexts that are NOT placed in the Public Domain!!
sample_size: 17
!!!!!!!!!!!!!!!!!
sample_size: 17
Shakespeare
sample_size: 17
!!!!!!!!!!!!!!!!!
sample_size: 17
*This Etext has certain copyright implications you should read!*
```

Having the empty lines filtering would be a great add on, thank you!

**Comment by loretoparisi** [comment]
@RdoubleA Thanks to helping me, I have two questions. If I use `batch_size=1` I can see different padding for the bath, it's possibile to test it using `shuffle=True`:

```
{'tokens': tensor([[128000,    220,   5161,     33,   6483,  22774,     13,    435,  11206,
           9282,     30, 128001]]), 'labels': tensor([[128000,    220,   5161,     33,   6483,  22774,     13,    435,  11206,
           9282,     30, 128001]])}
batch_size: 1
12   SEBASTIAN. Foul weather?

...

<torch.utils.data.dataloader.DataLoader object at 0x7fef40d26e50>
{'tokens': tensor([[128000,    262,  34776,    289,   2469,    279,   2606,    261,    315,
             26,    323,   4228,    433,    374, 128001]]), 'labels': tensor([[128000,    262,  34776,    289,   2469,    279,   2606,    261,    315,
             26,    323,   4228,    433,    374, 128001]])}
batch_size: 1
15     Than wots the miller of; and easy it is

```

And the same when using `batch_size=8` by example.
So if I use this dataset to train Llama3 from scratch I get a dimensionality error:

```
Epoch 0:   0%|                                                                                                                  | 0/2 [00:00<?, ?it/s][rank0]: Traceback (most recent call last):
[rank0]:   File "train.py", line 233, in <module>
[rank0]:     train()
[rank0]:   File "train.py", line 222, in train
[rank0]:     trainer.fit(model)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 543, in fit
[rank0]:     call._call_and_handle_interrupt(
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/call.py", line 43, in _call_and_handle_interrupt
[rank0]:     return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 105, in launch
[rank0]:     return function(*args, **kwargs)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 579, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 986, in _run
[rank0]:     results = self._run_stage()
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/trainer/trainer.py", line 1030, in _run_stage
[rank0]:     self.fit_loop.run()
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/loops/fit_loop.py", line 205, in run
[rank0]:     self.advance()
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/loops/fit_loop.py", line 363, in advance
[rank0]:     self.epoch_loop.run(self._data_fetcher)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 140, in run
[rank0]:     self.advance(data_fetcher)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 212, in advance
[rank0]:     batch, _, __ = next(data_fetcher)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/loops/fetchers.py", line 133, in __next__
[rank0]:     batch = super().__next__()
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/loops/fetchers.py", line 60, in __next__
[rank0]:     batch = next(self.iterator)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/utilities/combined_loader.py", line 341, in __next__
[rank0]:     out = next(self._iterator)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/lightning/pytorch/utilities/combined_loader.py", line 78, in __next__
[rank0]:     out[i] = next(self.iterators[i])
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
[rank0]:     raise exception
[rank0]: RuntimeError: Caught RuntimeError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 55, in fetch
[rank0]:     return self.collate_fn(data)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 317, in default_collate
[rank0]:     return collate(batch, collate_fn_map=default_collate_fn_map)
[rank0]:   File "/home/coder/.local/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 170, in collate
[rank0]:     raise RuntimeError('each element in list of batch should be of equal size')
[rank0]: RuntimeError: each element in list of batch should be of equal size
```

**Comment by loretoparisi** [comment]
This issue has been solved by https://github.com/pytorch/torchtune/issues/1416
