### ISSUE TITLE
Enable compile for batched RLHF generation utils 

### ISSUE THREAD

**Issue by SalmanMohammadi** [pytorch/torchtune#1402]
see parent issue. This issue is a real-time log of an amateur descent into compile debugging.

I'm compiling [my rlhf generation utils](https://github.com/SalmanMohammadi/torchtune/blob/optimize_generation_masking/torchtune/modules/rlhf/_generation.py), which uses kv-cacheing and iterative decoding (pls don't judge the code too hard, it needs cleaning up). However, compiled runs OOTB are significantly slower. It's worth noting the [main generation utils in torchtune](https://github.com/pytorch/torchtune/blob/main/torchtune/utils/_generation.py) do not exhibit this behaviour - compiled runs for this generation function provides ~10x speedups. The main difference in the RLHF generation utils is that it supports batched generation with varying sequence lengths which may be left-padded (thus needing custom attention masks and input position ids).

```bash
(tune) salman@combuter:~/torchtune$ python generate_test.py rlhf_compile
Warmup run!
Time for warmup: 23.83 sec
V0823 13:04:27.827000 148928 torch/_dynamo/guards.py:2688] [0/1] [__recompiles] Recompiling function generate_next_token_with_logits in /home/salman/torchtune/torchtune/modules/rlhf/_generation.py:37
V0823 13:04:27.827000 148928 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0823 13:04:27.827000 148928 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     - 0/0: tensor 'L['input_pos']' stride mismatch at index 0. expected 130, actual 192
Output:
 
...
Time for inference: 27.96 sec total, 21.78 tokens/sec
Bandwidth achieved: 112.15 GB/s
Memory used: 5.90 GB

(tune) salman@combuter:~/torchtune$ python generate_test.py rlhf
Output:
 
...
Time for inference: 5.49 sec total, 110.99 tokens/sec
Bandwidth achieved: 571.61 GB/s
Memory used: 5.21 GB

 ```
---
What's going on here? I tried setting the backend to cudagraphs and enable logging:
```python
I0823 14:22:20.582000 276899 torch/_inductor/cudagraph_trees.py:364] [__cudagraphs] recording cudagraph tree for graph without symints
V0823 14:22:20.726000 276899 torch/_inductor/cudagraph_trees.py:2099] [__cudagraphs] Running warmup of function 0
Time for warmup: 11.63 sec
V0823 14:22:20.848000 276899 torch/_dynamo/guards.py:2688] [0/1] [__recompiles] Recompiling function generate_next_token_with_logits in /home/salman/torchtune/torchtune/modules/rlhf/_generation.py:37
V0823 14:22:20.848000 276899 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0823 14:22:20.848000 276899 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     - 0/0: tensor 'L['input_pos']' stride mismatch at index 0. expected 356, actual 610
I0823 14:22:30.863000 276899 torch/_inductor/cudagraph_trees.py:364] [__cudagraphs] recording cudagraph tree for graph without symints
V0823 14:22:30.865000 276899 torch/_inductor/cudagraph_trees.py:2099] [__cudagraphs] Running warmup of function 1
V0823 14:22:30.955000 276899 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_inductor/cudagraph_trees.py:2282: UserWarning: Unable to hit fast path of CUDAGraphs because of pending, uninvoked backwards. Consider running with torch.no_grad() or using torch.compiler.cudagraph_mark_step_begin() before each model invocation
  warnings.warn(
V0823 14:22:31.048000 276899 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
V0823 14:22:31.141000 276899 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
V0823 14:22:31.229000 276899 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
... continues on max_generated_tokens times
```
wth??? It's not warmed up enough? And what's going on with this line?

```bash
/cudagraph_trees.py:2282: UserWarning: Unable to hit fast path of CUDAGraphs because of pending, uninvoked backwards. Consider running with torch.no_grad() or using torch.compiler.cudagraph_mark_step_begin() before each model invocation
```
`generate_with_logits` is decorated with `inference_mode` and I've wrapped with [`torch.no_grad`](https://github.com/SalmanMohammadi/torchtune/blob/9fc52e4d87d435c2c5265775c05b37fa8d0bd720/generate_test.py#L152). Calling ` torch.compiler.cudagraph_mark_step_begin()` fixed it but didn't change any other behaviour.

Anyway. I tried bumping up the number of generated tokens from 2 to 8 in the warmup run, but no avail!
```bash
Warmup run!
I0823 15:16:22.368000 363276 torch/_inductor/cudagraph_trees.py:364] [__cudagraphs] recording cudagraph tree for graph without symints
V0823 15:16:22.514000 363276 torch/_inductor/cudagraph_trees.py:2099] [__cudagraphs] Running warmup of function 0
V0823 15:16:22.604000 363276 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 0 because ancestor needed to warm up
V0823 15:16:22.691000 363276 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 0 because ancestor needed to warm up
V0823 15:16:22.786000 363276 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 0 because ancestor needed to warm up
V0823 15:16:22.871000 363276 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 0 because ancestor needed to warm up
V0823 15:16:22.951000 363276 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 0 because ancestor needed to warm up
V0823 15:16:23.037000 363276 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 0 because ancestor needed to warm up
Time for warmup: 12.33 sec
```

What about... another identical warmup run?? 
```python
Warmup run!
I0823 15:19:17.670000 367912 torch/_inductor/cudagraph_trees.py:364] [__cudagraphs] recording cudagraph tree for graph without symints
V0823 15:19:17.811000 367912 torch/_inductor/cudagraph_trees.py:2099] [__cudagraphs] Running warmup of function 0
Time for warmup: 12.00 sec
Warmup run2!
V0823 15:19:17.929000 367912 torch/_inductor/cudagraph_trees.py:2062] [__cudagraphs] Recording function 0 of graph recording id 0
Time for warmup: 0.37 sec
V0823 15:19:18.297000 367912 torch/_dynamo/guards.py:2688] [0/1] [__recompiles] Recompiling function generate_next_token_with_logits in /home/salman/torchtune/torchtune/modules/rlhf/_generation.py:37
V0823 15:19:18.297000 367912 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0823 15:19:18.297000 367912 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     - 0/0: tensor 'L['input_pos']' stride mismatch at index 0. expected 356, actual 386
I0823 15:19:28.334000 367912 torch/_inductor/cudagraph_trees.py:364] [__cudagraphs] recording cudagraph tree for graph without symints
V0823 15:19:28.335000 367912 torch/_inductor/cudagraph_trees.py:2099] [__cudagraphs] Running warmup of function 1
V0823 15:19:28.422000 367912 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
V0823 15:19:28.512000 367912 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
V0823 15:19:28.604000 367912 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
V0823 15:19:28.700000 367912 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
...
```

Okay. Still running in eager mode... what about 2 warmup runs, but in the second warmup run, we generate an additional token?
```python
Warmup run!
I0823 15:19:58.983000 369131 torch/_inductor/cudagraph_trees.py:364] [__cudagraphs] recording cudagraph tree for graph without symints
V0823 15:19:59.148000 369131 torch/_inductor/cudagraph_trees.py:2099] [__cudagraphs] Running warmup of function 0
Time for warmup: 11.51 sec
Warmup run2!
V0823 15:19:59.270000 369131 torch/_dynamo/guards.py:2688] [0/1] [__recompiles] Recompiling function generate_next_token_with_logits in /home/salman/torchtune/torchtune/modules/rlhf/_generation.py:37
V0823 15:19:59.270000 369131 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0823 15:19:59.270000 369131 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     - 0/0: tensor 'L['input_pos']' stride mismatch at index 0. expected 356, actual 357
I0823 15:20:09.373000 369131 torch/_inductor/cudagraph_trees.py:364] [__cudagraphs] recording cudagraph tree for graph without symints
V0823 15:20:09.375000 369131 torch/_inductor/cudagraph_trees.py:2099] [__cudagraphs] Running warmup of function 1
V0823 15:20:09.457000 369131 torch/_inductor/cudagraph_trees.py:2101] [__cudagraphs] Running eager of function 1 because ancestor needed to warm up
Time for warmup: 10.30 sec
V0823 15:20:09.570000 369131 torch/_inductor/cudagraph_trees.py:2062] [__cudagraphs] Recording function 1 of graph recording id 0
V0823 15:20:09.930000 369131 torch/_inductor/cudagraph_trees.py:2062] [__cudagraphs] Recording function 1 of graph recording id 1
V0823 15:20:10.197000 369131 torch/_inductor/cudagraph_trees.py:2062] [__cudagraphs] Recording function 1 of graph recording id 2
V0823 15:20:10.470000 369131 torch/_inductor/cudagraph_trees.py:2062] [__cudagraphs] Recording function 1 of graph recording id 3
...
V0823 15:20:15.041000 369131 torch/_inductor/cudagraph_trees.py:2062] [__cudagraphs] Recording function 1 of graph recording id 16
Traceback (most recent call last):
  File "/home/salman/torchtune/generate_test.py", line 176, in <module>
    generated_tokens, t = generate_rlhf_with_compile()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/torchtune/generate_test.py", line 156, in generate_rlhf_with_compile
    outputs, _ = rlhf.generate_with_logits(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/torchtune/torchtune/modules/rlhf/_generation.py", line 229, in generate_with_logits
    logits, tokens = custom_generate_next_token_with_logits(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 448, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/salman/torchtune/torchtune/modules/rlhf/_generation.py", line 37, in generate_next_token_with_logits
    def generate_next_token_with_logits(
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 615, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_functorch/aot_autograd.py", line 1034, in forward
    return compiled_fn(full_args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 321, in runtime_wrapper
    all_outs = call_func_at_runtime_with_args(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/utils.py", line 120, in call_func_at_runtime_with_args
    out = normalize_as_list(f(args))
                            ^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 500, in wrapper
    return compiled_fn(runtime_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_inductor/cudagraph_trees.py", line 361, in deferred_cudagraphify
    return fn(inputs)
           ^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_inductor/compile_fx.py", line 990, in run
    return model(new_inputs)
           ^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_inductor/cudagraph_trees.py", line 1868, in run
    out = self._run(new_inputs, function_id)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_inductor/cudagraph_trees.py", line 2037, in _run
    return self.record_function(new_inputs, function_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_inductor/cudagraph_trees.py", line 2068, in record_function
    node = CUDAGraphNode(
           ^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_inductor/cudagraph_trees.py", line 934, in __init__
    ] = self._record(wrapped_function.model, recording_inputs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/_inductor/cudagraph_trees.py", line 1154, in _record
    with preserve_rng_state(), torch.cuda.device(
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/cuda/graphs.py", line 186, in __exit__
    self.cuda_graph.capture_end()
  File "/home/salman/.pyenv/versions/3.11.9/envs/tune/lib/python3.11/site-packages/torch/cuda/graphs.py", line 84, in capture_end
    super().capture_end()
RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
```

Okay! No more eager mode. But OOM here. Let's switch back to inductor.
```bash
Warmup run!
Time for warmup: 23.85 sec
Warmup run2!
V0823 15:22:03.045000 371968 torch/_dynamo/guards.py:2688] [0/1] [__recompiles] Recompiling function generate_next_token_with_logits in /home/salman/torchtune/torchtune/modules/rlhf/_generation.py:37
V0823 15:22:03.045000 371968 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0823 15:22:03.045000 371968 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     - 0/0: tensor 'L['input_pos']' stride mismatch at index 0. expected 356, actual 357
Time for warmup: 22.00 sec
...
Time for inference: 6.56 sec total, 92.83 tokens/sec
Bandwidth achieved: 478.05 GB/s
Memory used: 5.95 GB
```

???

To recap where we're at so far, perf numbers w/o compile:
```bash
Time for inference: 5.47 sec total, 111.31 tokens/sec
Bandwidth achieved: 573.26 GB/s
Memory used: 5.21 GB
```
and with compile using the above settings:
```bash
Time for inference: 6.35 sec total, 95.85 tokens/sec
Bandwidth achieved: 493.60 GB/s
Memory used: 5.95 GB
```
So, still slower. Time to make sure there's nothing weird going on in the generation code. Stay tuned.

After some slight tuning in the generation code, we're now seeing the expected speedups with compile
```bash
Time for inference: 4.52 sec total, 134.72 tokens/sec
Bandwidth achieved: 693.81 GB/s
Memory used: 5.21 GB
```

but - we still need the two warmup passes!

As a sanity-check and baseline, the original torchtune generation utils give the following performance:

baseline:
Time for inference: 5.22 sec total, 116.62 tokens/sec
Bandwidth achieved: 600.57 GB/s
Memory used: 5.21 GB

compile - no warmup:
Time for inference: 27.97 sec total, 21.77 tokens/sec
Bandwidth achieved: 112.13 GB/s
Memory used: 5.21 GB

compile + warmup:
Time for inference: 4.75 sec total, 128.11 tokens/sec
Bandwidth achieved: 659.75 GB/s
Memory used: 5.21 GB
---

@ebsmothers @joecummings (not sure if you're tried compiling your batched generation?)

baseline:
Time for inference: 5.22 sec total, 116.62 tokens/sec
Bandwidth achieved: 600.57 GB/s
Memory used: 5.21 GB

compile - no warmup:
Time for inference: 27.97 sec total, 21.77 tokens/sec
Bandwidth achieved: 112.13 GB/s
Memory used: 5.21 GB

compile + warmup:
Time for inference: 4.75 sec total, 128.11 tokens/sec
Bandwidth achieved: 659.75 GB/s
Memory used: 5.21 GB
---

Interestingly, I don't get 

```bash
V0823 15:54:45.442000 423735 torch/_dynamo/guards.py:2688] [0/1] [__recompiles] Recompiling function generate_next_token_with_logits in /home/salman/torchtune/torchtune/modules/rlhf/_generation.py:37
V0823 15:54:45.442000 423735 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     triggered by the following guard failure(s):
V0823 15:54:45.442000 423735 torch/_dynamo/guards.py:2688] [0/1] [__recompiles]     - 0/0: tensor 'L['input_pos']' stride mismatch at index 0. expected 357, actual 358
```
When compiling with the existing utils.

Culprit found. So sorry if you've read this far. Closing this for now.

@ebsmothers @joecummings (not sure if you're tried compiling your batched generation?)

**Comment by SalmanMohammadi** [comment]
relevant issues? 
https://github.com/pytorch/pytorch/issues/120309#issuecomment-1991902257
https://github.com/pytorch/pytorch/issues/110666
