### ISSUE TITLE
No module named 'torchao.quantization.prototype'

### ISSUE THREAD

**Issue by JackWangCUMT** [pytorch/torchtune#1700]
No module named 'torchao.quantization.prototype'

**Comment by joecummings** [comment]
@JackWangCUMT Can you provide some more details?

**Comment by JackWangCUMT** [comment]
Package                Version
---------------------- -----------
aiohappyeyeballs       2.4.2
aiohttp                3.10.6
aiosignal              1.3.1
antlr4-python3-runtime 4.9.3
attrs                  24.2.0
blobfile               3.0.0
certifi                2024.8.30
charset-normalizer     3.3.2
colorama               0.4.6
datasets               3.0.1
dill                   0.3.8
filelock               3.16.1
frozenlist             1.4.1
fsspec                 2024.6.1
huggingface-hub        0.25.1
idna                   3.10
Jinja2                 3.1.4
lxml                   5.3.0
MarkupSafe             2.1.5
mpmath                 1.3.0
multidict              6.1.0
multiprocess           0.70.16
networkx               3.3
numpy                  1.26.4
omegaconf              2.3.0
packaging              24.1
pandas                 2.2.3
pillow                 10.4.0
pip                    24.2
pyarrow                17.0.0
pycryptodomex          3.20.0
python-dateutil        2.9.0.post0
pytz                   2024.2
PyYAML                 6.0.2
regex                  2024.9.11
requests               2.32.3
safetensors            0.4.5
sentencepiece          0.2.0
setuptools             75.1.0
six                    1.16.0
sympy                  1.13.3
tiktoken               0.7.0
torch                  2.4.1
torchao                0.1
torchtune              0.3.0
torchvision            0.19.1
tqdm                   4.66.5
typing_extensions      4.12.2
tzdata                 2024.2
urllib3                2.2.3
wheel                  0.44.0
xxhash                 3.5.0
yarl                   1.13.0


(I:\myconda\torchtune-lvm) I:\wm_net_folder\bigmodel\unsloth_llm>tune run lora_finetune_single_device --config qwen2_0.5B_lora_single_device.yaml
W0929 08:53:02.357000 10564 torch\distributed\elastic\multiprocessing\redirects.py:28] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "I:\myconda\torchtune-lvm\Scripts\tune.exe\__main__.py", line 7, in <module>
  File "I:\myconda\torchtune-lvm\Lib\site-packages\torchtune\_cli\tune.py", line 49, in main
    parser.run(args)
  File "I:\myconda\torchtune-lvm\Lib\site-packages\torchtune\_cli\tune.py", line 43, in run
    args.func(args)
  File "I:\myconda\torchtune-lvm\Lib\site-packages\torchtune\_cli\run.py", line 185, in _run_cmd
    self._run_single_device(args)
  File "I:\myconda\torchtune-lvm\Lib\site-packages\torchtune\_cli\run.py", line 94, in _run_single_device
    runpy.run_path(str(args.recipe), run_name="__main__")
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "I:\myconda\torchtune-lvm\Lib\site-packages\recipes\lora_finetune_single_device.py", line 21, in <module>
    from torchtune import config, modules, training, utils
  File "I:\myconda\torchtune-lvm\Lib\site-packages\torchtune\training\__init__.py", line 67, in <module>
    from torchtune.training.quantization import get_quantizer_mode
  File "I:\myconda\torchtune-lvm\Lib\site-packages\torchtune\training\quantization.py", line 25, in <module>
    from torchao.quantization.prototype.qat import (
ModuleNotFoundError: No module named 'torchao.quantization.prototype'

**Comment by ebsmothers** [comment]
Hi @JackWangCUMT I think your version of torchao is too old, you probably want 0.5 for things to work properly. How did you install it? I would recommend `pip install torchao`, I think that should give you 0.5.

**Comment by JackWangCUMT** [comment]
git clone https://github.com/pytorch/ao.git
cd ao
set USE_CPP=0
pip install -e .
Successfully installed torchao-0.6.0+git72d25183
