### ISSUE TITLE
self._loss_fn.ignore_index = -100 missing in the llama-3.1 tokenizer

### ISSUE THREAD

**Issue by Vattikondadheeraj** [pytorch/torchtune#1741]
Hey,

I found a bug in the tokenizer where the tokenizer is spiting an error when I am trying to decode self._loss_fn.ignore_index which is -100. I have attached the log file below. Let me know if I am missing something.

```
self._tokenizer.decode([-100])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/toolkit/scratch/LLMcode/Train/torchtune-3/torchtune/torchtune/models/llama3/_tokenizer.py", line 169, in decode
    return self.tt_model.decode(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/scratch/LLMcode/Train/torchtune-3/torchtune/torchtune/modules/tokenizers/_tiktoken.py", line 170, in decode
    return self.tt_model.decode(token_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/toolkit/.conda/envs/torch/lib/python3.11/site-packages/tiktoken/core.py", line 258, in decode
    return self._core_bpe.decode_bytes(tokens).decode("utf-8", errors=errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: out of range integral type conversion attempted
```

**Comment by RdoubleA** [comment]
Hi @Vattikondadheeraj, you can't decode -100 as it does not correspond to a real token id. It's simply a placeholder used when computing nn.CrossEntropyLoss to mask out certain labels from the loss and is not actually tied to real text. Is there something specific you are trying to decode?

**Comment by Vattikondadheeraj** [comment]
Hey @RdoubleA, Thanks!!! Actually I was trying to debug the input and the ground truth tokens for cross checking before sending it to the model and when I was trying to decode the labels, I was getting the above error because of the -100 token. But yeah thanks for the clarification. 


```
    def _prepare_sample(self, sample: Mapping[str, Any]) -> Dict[str, Any]:
        transformed_sample = self._message_transform(sample)
        if "messages" in transformed_sample:
            validate_messages(transformed_sample["messages"])

        tokenized_dict = self._model_transform(transformed_sample)

        if not ("tokens" in tokenized_dict and "mask" in tokenized_dict):
            keys_str = ", ".join(tokenized_dict.keys())
            error_message = (
                "model_transform returned the following keys: "
                f"{keys_str}. Must return 'tokens' and 'mask' as keys."
            )
            raise ValueError(error_message)

        # Wherever mask == True, set to CROSS_ENTROPY_IGNORE_IDX. Otherwise keep as tokens
        tokenized_dict["labels"] = list(
            np.where(
                tokenized_dict["mask"],
                CROSS_ENTROPY_IGNORE_IDX,
                tokenized_dict["tokens"],
            )
        )
        assert len(tokenized_dict["tokens"]) == len(tokenized_dict["labels"])

        return tokenized_dict
```

**Comment by RdoubleA** [comment]
Ah I see - if you decode the label tokens excluding the -100 you should get the expected model response from your dataset, or what you're training the model to respond with. You can also set `dataset.train_on_input=True` and there will be no -100 in the label tokens. Then when you decode it will also include the user prompt.
