### ISSUE TITLE
Cannot save models

### ISSUE THREAD

**Issue by zjost** [pytorch/torchtune#1762]
Hello!  I keep getting consistent errors whenever an epoch finishes and its time to save the model.  Torch version is 2.4.1+cu124.

Failures are typically non-informative in this case, so I've added some variables to try to get more insight and came up with the following command: :
```sh
TORCH_CPP_LOG_LEVEL=INFO TORCH_DISTRIBUTED_DEBUG=DETAIL NCCL_DEBUG=INFO NCCL_DEBUG_SUBSYS=INIT,ENV,GRAPH,COLL NCCL_SOCKET_IFNAME="eth0,en,eth,em,bond" tune run --nnodes 1 --nproc_per_node 3 lora_finetune_distributed --config ./recipes/mm_llama2_7B_lora.yaml
```

This is the tail of the logs:

```sh
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/recipes/lora_finetune_distributed.py", line 862, in <module>
[rank0]:     sys.exit(recipe_main())
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torchtune/config/_parse.py", line 99, in wrapper
[rank0]:     sys.exit(recipe_main(conf))
[rank0]:              ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/recipes/lora_finetune_distributed.py", line 857, in recipe_main
[rank0]:     recipe.train()
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/recipes/lora_finetune_distributed.py", line 823, in train
[rank0]:     self.save_checkpoint(epoch=curr_epoch)
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/recipes/lora_finetune_distributed.py", line 618, in save_checkpoint
[rank0]:     cpu_state_dict = training.get_full_model_state_dict(
[rank0]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torchtune/training/_distributed.py", line 424, in get_full_model_state_dict
[rank0]:     full_param = sharded_param.full_tensor()
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/_tensor/api.py", line 511, in full_tensor
[rank0]:     redist_res = self.redistribute(
[rank0]:                  ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/_tensor/api.py", line 483, in redistribute
[rank0]:     return Redistribute.apply(self, device_mesh, placements, async_op)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torch/autograd/function.py", line 574, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/_tensor/_redistribute.py", line 282, in forward
[rank0]:     output = redistribute_local_tensor(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/_tensor/_redistribute.py", line 188, in redistribute_local_tensor
[rank0]:     new_local_tensor = current_placement._to_replicate_tensor(
[rank0]:                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/_tensor/placement_types.py", line 234, in _to_replicate_tensor
[rank0]:     result = funcol.all_gather_tensor(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/_functional_collectives.py", line 203, in all_gather_tensor
[rank0]:     tensor = torch.ops._c10d_functional.all_gather_into_tensor(
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/zak_jost/lib/python3.11/site-packages/torch/_ops.py", line 1061, in __call__
[rank0]:     return self_._op(*args, **(kwargs or {}))
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: Backend nccl does not support allgather_into_tensor_coalesced
1|2|Loss: 1.743589997291565: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [13:55<00:00, 417.70s/it]
[I1007 22:53:00.305572040 TCPStoreLibUvBackend.cpp:115] [c10d - debug] Read callback failed. code:-4095 name:EOF desc:end of file
[I1007 22:53:00.335351548 TCPStoreLibUvBackend.cpp:115] [c10d - debug] Read callback failed. code:-4095 name:EOF desc:end of file
[I1007 22:53:00.370470289 TCPStoreLibUvBackend.cpp:115] [c10d - debug] Read callback failed. code:-4095 name:EOF desc:end of file
W1007 22:53:00.790000 139972489500480 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 8908 closing signal SIGTERM
E1007 22:53:00.904000 139972489500480 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 8907) of binary: /home/zak_jost/bin/python3.11
Traceback (most recent call last):
  File "/home/zak_jost/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zak_jost/lib/python3.11/site-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/zak_jost/lib/python3.11/site-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/zak_jost/lib/python3.11/site-packages/torchtune/_cli/run.py", line 194, in _run_cmd
    self._run_distributed(args, is_builtin=is_builtin)
  File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/zak_jost/lib/python3.11/site-packages/torchtune/_cli/run.py", line 95, in _run_distributed
    run(args)
  File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zak_jost/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/zak_jost/lib/python3.11/site-packages/recipes/lora_finetune_distributed.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-10-07_22:53:00
  host      : zak-jost-ray-training
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 8909)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-10-07_22:53:00
  host      : zak-jost-ray-training
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 8907)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
[I1007 22:53:00.811083325 TCPStoreLibUvBackend.cpp:115] [c10d - debug] Read callback failed. code:-4095 name:EOF desc:end of file
[I1007 22:53:00.811169886 TCPStoreLibUvBackend.cpp:1002] [c10d - debug] Store exit requested

[I1007 22:53:00.811187377 TCPStoreLibUvBackend.cpp:1070] [c10d - debug] UV main loop done: res:1
[I1007 22:53:00.811200287 TCPStoreLibUvBackend.cpp:1076] [c10d - debug] Walking live handles prior to closing clients
[I1007 22:53:00.811211947 TCPStoreLibUvBackend.cpp:1059] [c10d - debug] UV live handle type 12 active:1 is-closing:0
[I1007 22:53:00.811221437 TCPStoreLibUvBackend.cpp:1086] [c10d - debug] Walking live handles after closing clients
[I1007 22:53:00.811232467 TCPStoreLibUvBackend.cpp:1059] [c10d - debug] UV live handle type 12 active:0 is-closing:1
[I1007 22:53:00.811243977 TCPStoreLibUvBackend.cpp:1095] [c10d] uv_loop_close failed with:-16 errn:EBUSY desc:resource busy or locked
[I1007 22:53:00.811275138 TCPStoreLibUvBackend.cpp:1105] [c10d] uv_loop cleanup finished.
```

Any ideas?

**Comment by joecummings** [comment]
Hey @zjost, thanks for bringing this to our attention. Could I also ask which torchtune version you're using and for the config?

**Comment by zjost** [comment]
Yes, should have included that, sorry: `torchtune==0.3.1`

I've tried multiple recipes, but here's an example that's mostly stock with two exceptions:

- Changed filepaths to my local directory instead of `/tmp/...`
- Changed `max_steps_per_epoch: 1` to invoke saving the model ASAP

```yaml
# Model Arguments
model:
  _component_: torchtune.models.llama2.lora_llama2_7b
  lora_attn_modules: ['q_proj', 'v_proj']
  apply_lora_to_mlp: False
  apply_lora_to_output: False
  lora_rank: 8
  lora_alpha: 16
  lora_dropout: 0.0

tokenizer:
  _component_: torchtune.models.llama2.llama2_tokenizer
  path: ./models/Llama-2-7b-hf/tokenizer.model
  max_seq_len: null

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: ./models/Llama-2-7b-hf
  checkpoint_files: [
    pytorch_model-00001-of-00002.bin,
    pytorch_model-00002-of-00002.bin
  ]
  adapter_checkpoint: null
  recipe_checkpoint: null
  output_dir: ./models/Llama-2-7b-hf
  model_type: LLAMA2
resume_from_checkpoint: False
save_adapter_weights_only: False

# Dataset and Sampler
dataset:
  _component_: torchtune.datasets.alpaca_cleaned_dataset
seed: null
shuffle: True
batch_size: 2

# Optimizer and Scheduler
optimizer:
  _component_: torch.optim.AdamW
  fused: True
  weight_decay: 0.01
  lr: 3e-4
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Training
epochs: 1
max_steps_per_epoch: 1
gradient_accumulation_steps: 32

# Logging
output_dir: ./models/lora_finetune_output
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: ${output_dir}
log_every_n_steps: 1
log_peak_memory_stats: False

# Environment
device: cuda
dtype: bf16
enable_activation_checkpointing: False

# Show case the usage of pytorch profiler
# Set enabled to False as it's only needed for debugging training
profiler:
  _component_: torchtune.training.setup_torch_profiler

  enabled: False

  #Output directory of trace artifacts
  output_dir: ${output_dir}/profiling_outputs

  #`torch.profiler.ProfilerActivity` types to trace
  cpu: True
  cuda: True

  #trace options passed to `torch.profiler.profile`
  profile_memory: False
  with_stack: False
  record_shapes: True
  with_flops: False

  # `torch.profiler.schedule` options:
  # wait_steps -> wait, warmup_steps -> warmup, active_steps -> active, num_cycles -> repeat
  wait_steps: 5
  warmup_steps: 5
  active_steps: 2
  num_cycles: 1
```

**Comment by zjost** [comment]
I'm wondering if this is a PyTorch issue.  Perhaps related to: https://github.com/pytorch/pytorch/issues/111187

**Comment by zjost** [comment]
Update: 
It seems the error has gone away if I don't use the debugging variables in the launch command, and have the nightly versions of both torchtune and pytorch.

Specifically, this works:
```sh
TORCH_CPP_LOG_LEVEL=INFO NCCL_DEBUG=INFO tune run --nnodes 1 --nproc_per_node 2 lora_finetune_distributed --config ./recipes/mm_phi3_lora.yaml
```

And this fails:
```sh
TORCH_CPP_LOG_LEVEL=INFO TORCH_DISTRIBUTED_DEBUG=DETAIL NCCL_DEBUG=INFO tune run --nnodes 1 --nproc_per_node 2 lora_finetune_distributed --config ./recipes/mm_phi3_lora.yaml
```

The only difference being that I've removed `TORCH_DISTRIBUTED_DEBUG=DETAIL`.

I suppose this means that the real error was something different, and adding this variable caused a different problem.

**Comment by ebsmothers** [comment]
Thanks @zjost for debugging and providing the update here. I'll close this issue since I think things have been triaged in https://github.com/pytorch/pytorch/issues/137505. Ofc if you are still running into issues on the torchtune side of things please reopen and we can investigate further.
