### ISSUE TITLE
error when `tune run 8B_lora_single_device`

### ISSUE THREAD

**Issue by maswadkar** [pytorch/torchtune#1821]
I followed step by step process for finetuning llama 3.1 8B instruct model on single device(RTX4090) 

- I downloaded the model using llama-stack (https://github.com/meta-llama/llama-stack/blob/main/docs/cli_reference.md)
- trying to finetune on chat dataset using tutorial  https://pytorch.org/torchtune/main/tutorials/chat.html
- error is thrown on the last step of `tune run lora_finetune_single_device --config 8B_lora_single_device.yaml epochs=15`

the error is
```
INFO:torchtune.utils._logging:Running LoRAFinetuneRecipeSingleDevice with resolved config:

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /workspace/.llama/checkpoints/Llama3.1-8B-Instruct/
  checkpoint_files:
  - model-00001-of-00004.safetensors
  - model-00002-of-00004.safetensors
  - model-00003-of-00004.safetensors
  - model-00004-of-00004.safetensors
  model_type: LLAMA3
  output_dir: /workspace/.llama/checkpoints/Llama3.1-8B-Instruct/
  recipe_checkpoint: null
compile: false
dataset:
  _component_: torchtune.datasets.chat_dataset
  conversation_column: dialogue
  conversation_style: sharegpt
  data_files: mydata.json
  source: json
  split: train
device: cuda
dtype: bf16
enable_activation_checkpointing: true
enable_activation_offloading: false
epochs: 15
gradient_accumulation_steps: 64
log_every_n_steps: 1
log_peak_memory_stats: false
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
lr_scheduler:
  _component_: torchtune.modules.get_cosine_schedule_with_warmup
  num_warmup_steps: 100
max_steps_per_epoch: null
metric_logger:
  _component_: torchtune.training.metric_logging.DiskLogger
  log_dir: /tmp/lora_finetune_output
model:
  _component_: torchtune.models.llama3_1.lora_llama3_1_8b
  apply_lora_to_mlp: false
  apply_lora_to_output: false
  lora_alpha: 16
  lora_attn_modules:
  - q_proj
  - v_proj
  lora_dropout: 0.0
  lora_rank: 8
optimizer:
  _component_: torch.optim.AdamW
  fused: true
  lr: 0.0003
  weight_decay: 0.01
output_dir: /tmp/lora_finetune_output
profiler:
  _component_: torchtune.training.setup_torch_profiler
  active_steps: 2
  cpu: true
  cuda: true
  enabled: false
  num_cycles: 1
  output_dir: /tmp/lora_finetune_output/profiling_outputs
  profile_memory: false
  record_shapes: true
  wait_steps: 5
  warmup_steps: 5
  with_flops: false
  with_stack: false
resume_from_checkpoint: false
save_adapter_weights_only: false
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  max_seq_len: null
  path: /workspace/.llama/checkpoints/Llama3.1-8B-Instruct/tokenizer.model

Traceback (most recent call last):
  File "/usr/local/bin/tune", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/_cli/run.py", line 196, in _run_cmd
    self._run_single_device(args, is_builtin=is_builtin)
  File "/usr/local/lib/python3.10/dist-packages/torchtune/_cli/run.py", line 102, in _run_single_device
    runpy.run_path(str(args.recipe), run_name="__main__")
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/recipes/lora_finetune_single_device.py", line 793, in <module>
    sys.exit(recipe_main())
  File "/usr/local/lib/python3.10/dist-packages/torchtune/config/_parse.py", line 99, in wrapper
    sys.exit(recipe_main(conf))
  File "/usr/local/lib/python3.10/dist-packages/recipes/lora_finetune_single_device.py", line 786, in recipe_main
    recipe = LoRAFinetuneRecipeSingleDevice(cfg=cfg)
  File "/usr/local/lib/python3.10/dist-packages/recipes/lora_finetune_single_device.py", line 146, in __init__
    self.seed = training.set_seed(seed=cfg.seed)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 355, in __getattr__
    self._format_and_raise(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 351, in __getattr__
    return self._get_impl(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
  File "/usr/local/lib/python3.10/dist-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigAttributeError: Missing key seed
    full_key: seed
    object_type=dict
```

**Comment by RdoubleA** [comment]
Hi @maswadkar , is this a config you copied over with `tune cp`? It looks like the config is missing the seed field, which we usually just set to `seed: null`. It might've been accidentally deleted. Could you try running again after updating the 8B_lora_finetune_single_device.yaml with the seed field?

**Comment by maswadkar** [comment]
Million thanks for such a quick and precise answer. 
I figured that out. 
But seems I cannot finetune a model that i downloaded using `tune download ...`

I need to get only HF (huggingface model)  to use `tune run`

I will keep trying... 

If no answer, I will close the issue then.

**Comment by RdoubleA** [comment]
We typically download the Hugging Face model via `tune download`. Were you not able to launch a run after adding the seed parameter? What is the error you are seeing now?

**Comment by maswadkar** [comment]
I mean to say I downloaded the model using 

```
pip install -Uq llama-stack
llama download --source meta --model-id $MODEL_ID --meta-url $META_URL
```

once I fixed the error of seed.... I encountered issue of missing `config.json` where i realized that this file is available in model folder only if i have it from HF and not directly from source meta. 

for now i concluded that using torchtune you can train only the HF models... and not the one from source=meta
Please correct me if I am wrong

**Comment by felipemello1** [comment]
@maswadkar , i am not 100% sure. @pbontrager would know better. But I think you would have to change from

```checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer```
  
  to
  
  ```
  checkpointer:
  _component_: torchtune.training.FullModelMetaCheckpointer
  ```

**Comment by maswadkar** [comment]
I will try with this change tomorrow... 
until then, Can i keep the Issue open... or should i close it. 

additional question, after the finetuning is done... will i still be able to serve the model using 

`llama stack run <uniq_build_name> --port PORT` 
that was created using `llama stack build ` and `llama stack configure`

**Comment by pbontrager** [comment]
Yes, keep open until you've proven that you have it working now. I believe that your model should work with llama stack afterward because it's in the original meta format, but don't test this or make any claims around this.

**Comment by maswadkar** [comment]
Hi Again,

finetune worked successully 👍🏼 
million thanks !!

I am running evaluation `tune cp eleuther_evaluation` now 


the initial download had `consolidated.00.pth` file 
after finetuning i got `adapter_0.pt meta_model_0.pt`

hope .pt and .pth should not make any problem

**Comment by maswadkar** [comment]
just a note... 
when i added both file in config `checkpoint_files: [adapter_0.pt, meta_model_0.pt]`
it errored out. 

then i changed config to `checkpoint_files: [meta_model_0.pt]`

it worked

**Comment by maswadkar** [comment]
can i just rename `meta_model_0.pt` to `consolidated.00.pth` to serve the model via `llama stack run  <my-stack>`
