### ISSUE TITLE
CUDA error with <bitsandbytes.optim.PagedAdamW> optimzier

### ISSUE THREAD

**Issue by shawnricecake** [pytorch/torchtune#1856]
Hi,

I used the config named `recipes/configs/mistral/7B_full_low_memory.yaml`

the default optimizer inside is `bitsandbytes.optim.PagedAdamW`, which will raise the error as follows, 

```
[rank6]: Traceback (most recent call last):
[rank6]:   File "/sensei-fs/users/my_name/code/finetune/finetune_distributed.py", line 776, in <module>
[rank6]:     sys.exit(recipe_main())
[rank6]:   File "/sensei-fs/users/my_name/code/finetune/torchtune/torchtune/config/_parse.py", line 99, in wrapper
[rank6]:     sys.exit(recipe_main(conf))
[rank6]:   File "/sensei-fs/users/my_name/code/finetune/finetune_distributed.py", line 771, in recipe_main
[rank6]:     recipe.train()
[rank6]:   File "/sensei-fs/users/my_name/code/finetune/finetune_distributed.py", line 680, in train
[rank6]:     self._optimizer.step()
[rank6]:   File "/opt/venv/lib/python3.10/site-packages/torch/optim/optimizer.py", line 484, in wrapper
[rank6]:     out = func(*args, **kwargs)
[rank6]:   File "/opt/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank6]:     return func(*args, **kwargs)
[rank6]:   File "/opt/venv/lib/python3.10/site-packages/bitsandbytes/optim/optimizer.py", line 292, in step
[rank6]:     torch.cuda.synchronize()
[rank6]:   File "/opt/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 892, in synchronize
[rank6]:     return torch._C._cuda_synchronize()
[rank6]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank6]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank6]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank6]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by pbontrager** [comment]
Can you share the full command you ran along with some environment details such as your pytorch, cuda, and bitandbytes versions?

**Comment by shawnricecake** [comment]
> Can you share the full command you ran along with some environment details such as your pytorch, cuda, and bitandbytes versions?

Sorry, I forgot that.

The environment is as follows,
```
torch == 2.4.0+cu124
bitandbytes == 0.44.1
CUDA == 12.4
GPU == H100
```

**Comment by bradhilton** [comment]
I'm also seeing this error

**Comment by ebsmothers** [comment]
Hi @bradhilton thanks for the bump (looks like this one slipped through the cracks.. sorry about that @shawnricecake). Same question for you -- can you share details of your environment? When I run `tune run full_finetune_single_device --config mistral/7B_full_low_memory` on an A100 with a source torchtune install and torch/torchao nightlies on CUDA 12.4 with 0.44.1 bitsandbytes version I don't have any problems.

**Comment by bradhilton** [comment]
Here's where I'm reproducing the issue. If I run `tune run full_finetune_distributed --config ./config.yaml` where my config file is the vanilla `llama3_1/8B_full` with the following changes to 3 lines:

```yaml
...
# Tokenizer
tokenizer:
  _component_: torchtune.models.llama3.llama3_tokenizer
  # changed tokenizer path
  path: /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/llama_models/llama3/api/tokenizer.model
  max_seq_len: null
  
...

checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  # changed checkpoint directory
  checkpoint_dir: /tmp/Hermes-2-Theta-Llama-3-8B/
  checkpoint_files: [
    model-00001-of-00004.safetensors,
    model-00002-of-00004.safetensors,
    model-00003-of-00004.safetensors,
    model-00004-of-00004.safetensors
  ]
  recipe_checkpoint: null
  # changed output_dir
  output_dir: /tmp/Hermes-2-Theta-Llama-3-8B/
  model_type: LLAMA3
  
...
```

Then everything works fine 👌

However if I change the optimizer:

```yaml
...

optimizer:
  _component_: bitsandbytes.optim.PagedAdamW
  lr: 2e-5
  
...
```

I get the CUDA error:

```python
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 918, in <module>
[rank0]:     sys.exit(recipe_main())
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/config/_parse.py", line 99, in wrapper
[rank0]:     sys.exit(recipe_main(conf))
[rank0]:              ^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 913, in recipe_main
[rank0]:     recipe.train()
[rank0]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 815, in train
[rank0]:     self._optimizer.step()
[rank0]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 484, in wrapper
[rank0]:     out = func(*args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/bitsandbytes/optim/optimizer.py", line 292, in step
[rank0]:     torch.cuda.synchronize()
[rank0]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 892, in synchronize
[rank0]:     return torch._C._cuda_synchronize()
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank0]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank0]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 918, in <module>
[rank1]:     sys.exit(recipe_main())
[rank1]:              ^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/config/_parse.py", line 99, in wrapper
[rank1]:     sys.exit(recipe_main(conf))
[rank1]:              ^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 913, in recipe_main
[rank1]:     recipe.train()
[rank1]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/recipes/full_finetune_distributed.py", line 815, in train
[rank1]:     self._optimizer.step()
[rank1]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/optim/optimizer.py", line 484, in wrapper
[rank1]:     out = func(*args, **kwargs)
[rank1]:           ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank1]:     return func(*args, **kwargs)
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^
[rank1]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/bitsandbytes/optim/optimizer.py", line 292, in step
[rank1]:     torch.cuda.synchronize()
[rank1]:   File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 892, in synchronize
[rank1]:     return torch._C._cuda_synchronize()
[rank1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank1]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank1]: CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
[rank1]: For debugging consider passing CUDA_LAUNCH_BLOCKING=1
[rank1]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7645cfecbf86 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7645cfe7ad10 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7645cffa6f08 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1da06 (0x7645cff71a06 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x1f783 (0x7645cff73783 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x1fac2 (0x7645cff73ac2 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #6: <unknown function> + 0x5dd3d0 (0x7645cdbdd3d0 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x6abdf (0x7645cfeafbdf in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x21b (0x7645cfea8c3b in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #9: c10::TensorImpl::~TensorImpl() + 0x9 (0x7645cfea8de9 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #10: <unknown function> + 0x899b88 (0x7645cde99b88 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #11: THPVariable_subclass_dealloc(_object*) + 0x2e0 (0x7645cde99ef0 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #24: <unknown function> + 0x29d90 (0x7645d0829d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #25: __libc_start_main + 0x80 (0x7645d0829e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #26: _start + 0x29 (0x6000a9 in /home/ubuntu/atreides/.venv/bin/python3)

terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x79bed539af86 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x79bed5349d10 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x79bed5475f08 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1da06 (0x79bed5440a06 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #4: <unknown function> + 0x1f783 (0x79bed5442783 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x1fac2 (0x79bed5442ac2 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #6: <unknown function> + 0x5dd3d0 (0x79bed31dd3d0 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #7: <unknown function> + 0x6abdf (0x79bed537ebdf in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #8: c10::TensorImpl::~TensorImpl() + 0x21b (0x79bed5377c3b in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #9: c10::TensorImpl::~TensorImpl() + 0x9 (0x79bed5377de9 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #10: <unknown function> + 0x899b88 (0x79bed3499b88 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
frame #11: THPVariable_subclass_dealloc(_object*) + 0x2e0 (0x79bed3499ef0 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #24: <unknown function> + 0x29d90 (0x79bed5e29d90 in /lib/x86_64-linux-gnu/libc.so.6)
frame #25: __libc_start_main + 0x80 (0x79bed5e29e40 in /lib/x86_64-linux-gnu/libc.so.6)
frame #26: _start + 0x29 (0x6000a9 in /home/ubuntu/atreides/.venv/bin/python3)

W1126 15:11:49.348000 133725523257152 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 22974 closing signal SIGTERM
E1126 15:11:49.379000 133725523257152 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -6) local_rank: 0 (pid: 22973) of binary: /home/ubuntu/atreides/.venv/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/atreides/.venv/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/_cli/run.py", line 206, in _run_cmd
    self._run_distributed(args, is_builtin=is_builtin)
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/_cli/run.py", line 95, in _run_distributed
    run(args)
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

@ebsmothers This is running on 2xH100s/CUDA 12.4 with the following package versions:

```
bitsandbytes==0.44.1
torch==2.4.0
torchao==0.6.1
torchtune == 0.4.0
```

@felipemello1 Reducing the batch size or sequence length does not help. Watching Nvidia-smi indicates that there is plenty of memory headroom before the illegal memory access is encountered. Appears to peak just above ~30GB out of ~80GB before terminating.

Seems to affect all bitsandbytes optimizers I've tried (Adam, AdamW, PagedAdamW, PagedAdamW8Bit) 

Running with CUDA_LAUNCH_BLOCKING=1 gives the following output:
```python
Error an illegal memory access was encountered at line 113 in file /src/csrc/ops.cu
[rank0]:[E1126 15:19:49.688494806 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 0] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7a8ac97cbf86 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7a8ac977ad10 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7a8ac98a6f08 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7a8a7a9c33e6 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7a8a7a9c8600 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7a8a7a9cf2ba in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7a8a7a9d16fc in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xdc253 (0x7a8ac84dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x7a8aca294ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7a8aca326850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 0 (default_pg) Rank 0] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7a8ac97cbf86 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7a8ac977ad10 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7a8ac98a6f08 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7a8a7a9c33e6 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7a8a7a9c8600 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7a8a7a9cf2ba in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7a8a7a9d16fc in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xdc253 (0x7a8ac84dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x7a8aca294ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7a8aca326850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1521 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7a8ac97cbf86 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe5aa84 (0x7a8a7a65aa84 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xdc253 (0x7a8ac84dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #3: <unknown function> + 0x94ac3 (0x7a8aca294ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7a8aca326850 in /lib/x86_64-linux-gnu/libc.so.6)

Error an illegal memory access was encountered at line 113 in file /src/csrc/ops.cu
[rank1]:[E1126 15:19:49.735407831 ProcessGroupNCCL.cpp:1515] [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f9ce26cbf86 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f9ce267ad10 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f9ce27a6f08 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f9c937c33e6 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f9c937c8600 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7f9c937cf2ba in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f9c937d16fc in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xdc253 (0x7f9ce12dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x7f9ce3094ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7f9ce3126850 in /lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 0 (default_pg) Rank 1] Process group watchdog thread terminated with exception: CUDA error: an illegal memory access was encountered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:43 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f9ce26cbf86 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f9ce267ad10 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(int, char const*, char const*, int, bool) + 0x118 (0x7f9ce27a6f08 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x56 (0x7f9c937c33e6 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0xa0 (0x7f9c937c8600 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #5: c10d::ProcessGroupNCCL::watchdogHandler() + 0x1da (0x7f9c937cf2ba in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #6: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x10c (0x7f9c937d16fc in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #7: <unknown function> + 0xdc253 (0x7f9ce12dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x94ac3 (0x7f9ce3094ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0x126850 (0x7f9ce3126850 in /lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1521 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x96 (0x7f9ce26cbf86 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0xe5aa84 (0x7f9c9345aa84 in /home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xdc253 (0x7f9ce12dc253 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #3: <unknown function> + 0x94ac3 (0x7f9ce3094ac3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #4: <unknown function> + 0x126850 (0x7f9ce3126850 in /lib/x86_64-linux-gnu/libc.so.6)

W1126 15:19:49.762000 124063589377856 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 27781 closing signal SIGTERM
E1126 15:19:49.826000 124063589377856 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -6) local_rank: 0 (pid: 27780) of binary: /home/ubuntu/atreides/.venv/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/atreides/.venv/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/_cli/run.py", line 206, in _run_cmd
    self._run_distributed(args, is_builtin=is_builtin)
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torchtune/_cli/run.py", line 95, in _run_distributed
    run(args)
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/atreides/.venv/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

**Comment by felipemello1** [comment]
oh, now i see! I believe that PagedAdamW is not compatible with FSDP2 (what we use for the distributed recipe). You could confirm it with bitsandbytes, but as an alternative, you can take a look at [torchao's optimizers](https://github.com/pytorch/ao/tree/5eb6339e0b6f413c74a3dfd5e7f53449474723fc/torchao/prototype/low_bit_optim), which do work with FSDP2.
