### ISSUE TITLE
NCCL operations have failed or timed out.

### ISSUE THREAD

**Issue by Ljyustc** [pytorch/torchtune#2059]
Hi, I am fine-tuning the Llama3.1-8B-Instruct on the alpaca_dataset using the original receipt 'llama3_1/8B_full' in a distributed setup. The issue occurs during the first epoch, around 70% progress. The training crashes with the following error message:
```
[rank0]:[E1124 03:56:40.319632467 ProcessGroupNCCL.cpp:692] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=13573, OpType=_ALLGATHER_BASE, NumelIn=54528000, NumelOut=218112000, Timeout(ms)=600000) ran for 600045 milliseconds before timing out.
[rank0]:[E1124 03:56:40.319685792 ProcessGroupNCCL.cpp:715] Stack trace of the timedout collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank0]:[E1124 03:56:40.320665034 ProcessGroupNCCL.cpp:1996] [PG ID 0 PG GUID 0(default_pg) Rank 0] Work timeout is detected by watchdog at work: 13573, last enqueued NCCL work: 13578, last completed NCCL work: 13572.
[rank2]:[E1124 03:56:40.340505126 ProcessGroupNCCL.cpp:692] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=13573, OpType=_ALLGATHER_BASE, NumelIn=54528000, NumelOut=218112000, Timeout(ms)=600000) ran for 600066 milliseconds before timing out.
[rank2]:[E1124 03:56:40.340557131 ProcessGroupNCCL.cpp:715] Stack trace of the timedout collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank2]:[E1124 03:56:40.340790398 ProcessGroupNCCL.cpp:1996] [PG ID 0 PG GUID 0(default_pg) Rank 2] Work timeout is detected by watchdog at work: 13573, last enqueued NCCL work: 13578, last completed NCCL work: 13572.
[rank1]:[E1124 03:56:40.350759226 ProcessGroupNCCL.cpp:692] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=13573, OpType=_ALLGATHER_BASE, NumelIn=54528000, NumelOut=218112000, Timeout(ms)=600000) ran for 600076 milliseconds before timing out.
[rank1]:[E1124 03:56:40.350807309 ProcessGroupNCCL.cpp:715] Stack trace of the timedout collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank1]:[E1124 03:56:40.351043623 ProcessGroupNCCL.cpp:1996] [PG ID 0 PG GUID 0(default_pg) Rank 1] Work timeout is detected by watchdog at work: 13573, last enqueued NCCL work: 13578, last completed NCCL work: 13572.
[rank3]:[E1124 03:56:40.366366174 ProcessGroupNCCL.cpp:692] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=13575, OpType=_REDUCE_SCATTER_BASE, NumelIn=4096, NumelOut=1024, Timeout(ms)=600000) ran for 600002 milliseconds before timing out.
[rank3]:[E1124 03:56:40.366412348 ProcessGroupNCCL.cpp:715] Stack trace of the timedout collective not found, potentially because FlightRecorder is disabled. You can enable it by setting TORCH_NCCL_TRACE_BUFFER_SIZE to a non-zero value.
[rank3]:[E1124 03:56:40.366644911 ProcessGroupNCCL.cpp:1996] [PG ID 0 PG GUID 0(default_pg) Rank 3] Work timeout is detected by watchdog at work: 13575, last enqueued NCCL work: 13576, last completed NCCL work: 13574.
[rank3]:[E1124 03:56:40.999486383 ProcessGroupNCCL.cpp:734] [Rank 3] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank3]:[E1124 03:56:40.999499542 ProcessGroupNCCL.cpp:748] [Rank 3] To avoid data inconsistency, we are taking the entire process down.
```
Environment
- torch version: 2.4.0 (I have also tried 2.6.0)
- CUDA version: 12.1
- GPUs: 4x NVIDIA A800 80GB

What I’ve Tried
- Added the following environment variables:
```
export NCCL_P2P_LEVEL=NVL
export NCCL_P2P_DISABLE=1
export NCCL_IB_GID_INDEX=3
```

Surprisingly, when I reduce the training dataset size by setting 'split: train[75%:]', the training completes without any issues, indicating that this might not be caused by a bug in the training script logic itself.

**Comment by albertbn** [comment]
Hey, I have a similar issue detailed [here](https://github.com/pytorch/torchtune/issues/2059)

For me it's consistent, `torchtune, torch` and the rest of the torch family packages are up to date with stable releases.

In my case I am running LoRa tuning for Llama 3.1 70B on 8xV100 (32GB) GPUS. The training completes successfully, but the `WorkNCCL` timeout happens always at `Saving checkpoint`.

I've also tried setting the `NCCL` env variables mentioned above in addition to others with no success. 

Another thing I've noticed is: When loading the 70B model into cuda memory - I see 8 CPU heavy processes which obviously do the work of loading the model and moving it to cuda - one for each GPU. Nevertheless, after training completes, I see *only a single heavy CPU process*, that probably tries to convert the weights from all 8 cuda GPUs to CPU to ultimately save them to disk.  

```
1|101|Loss: 0.13964782655239105: 100%|█████████████████████████████████████████████████████████████| 101/101 [1:54:39<00:00, 69.96s/it]INFO:torchtune.utils._logging:Saving checkpoint. This may take some time. Retrieving full model state dict...
INFO:torchtune.utils._logging:Getting full model state dict took 114.73 secs
[rank4]:[E1129 11:56:57.204055508 ProcessGroupNCCL.cpp:616] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=28956, OpType=ALLREDUCE, NumelIn=1, NumelOut=1, Timeout(ms)=600000) ran for 600022 milliseconds before timing out.
...

Traceback (most recent call last):
  File "/home/ubuntu/projects/models/venv3/bin/tune", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/torchtune/_cli/tune.py", line 49, in main
    parser.run(args)
  File "/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/torchtune/_cli/tune.py", line 43, in run
    args.func(args)
  File "/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/torchtune/_cli/run.py", line 206, in _run_cmd
    self._run_distributed(args, is_builtin=is_builtin)
  File "/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/torchtune/_cli/run.py", line 95, in _run_distributed
    run(args)
  File "/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/ubuntu/projects/models/venv3/lib/python3.12/site-packages/recipes/lora_finetune_distributed.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-11-29_13:49:01
  host      : ip-172-31-12-154.us-west-2.compute.internal
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 59620)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by Ljyustc** [comment]
Yes, the issue occurs consistently on my end, and it happens with a specific batch of data every time. I’ve noticed that training works fine on a single GPU, which suggests the problem lies with the data in distributed training. 

To investigate further, I printed out the data for each batch. The issue doesn't seem to stem from the data content itself, but rather when the output lengths of the batches processed on two GPUs are significantly different. For example, in the problematic batch, the output length on GPU 0 is 515, while on GPU 1 it is only 18. In other cases, the output lengths on both GPUs are more consistent. By skipping this problematic batch, the training continues without issue. As a solution, I rearrange the data lengths to avoid this mismatch.



> Hi @Ljyustc thanks for creating the issue. Just to confirm, does the timeout occur consistently across multiple runs? If so, can you log the indices of training samples at the beginning of each step to see what samples are in the batch where the hang occurs? (Btw separately I’d recommend to always use at least the latest stable version of PyTorch if possible, as that’s where we’ll be able to provide the best support)

**Comment by felipemello1** [comment]
@Ljyustc thanks for investigating it. Would you like to try setting dataset.packed=True? This would pack your samples, and every batch would have the same sequence length, increasing GPU utilization greatly. You can see results here: https://github.com/pytorch/torchtune#optimization-flags

@ebsmothers @pbontrager , to avoid this issue when packed=False, maybe we should add a barrier at the end of the steps?
