### ISSUE TITLE
Installing torch through the requirements.txt file always causes issues

### ISSUE THREAD

**Issue by kartikayk** [pytorch/torchtune#412]
I've tried this a number of different times and ways, but I always run into issues when I try to install torch from the requirements.txt file. I'll summarize everything I tried below

## Try 1: Follow the readme

```
conda create -n torchtune_new python=3.10
conda activate torchtune_new
pip install -e .

tune download
```

Output:
```
Traceback (most recent call last):
  File "/home/kartikayk/.conda/envs/torchtune_new/bin/tune", line 5, in <module>
    from torchtune._cli.cli_utils.tune import main
  File "/home/kartikayk/torchtune/torchtune/__init__.py", line 7, in <module>
    from torchtune import datasets, models, modules, utils
  File "/home/kartikayk/torchtune/torchtune/datasets/__init__.py", line 7, in <module>
    from torch.utils.data import Dataset
  File "/home/kartikayk/.conda/envs/torchtune_new/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/kartikayk/.conda/envs/torchtune_new/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkAddData_12_1, version libnvJitLink.so.12
```

## Try 2: Manually install PyTorch

```
conda deactivate
conda remove --name torchtune_new --all

conda create -n torchtune_new python=3.10
conda activate torchtune_new

conda install pytorch pytorch-cuda=12.1 -c pytorch -c nvidia

pip install -e .

tune download
```

Output:

```
usage: download.py [-h] --repo-id REPO_ID [--output-dir OUTPUT_DIR] [--hf-token HF_TOKEN]
download.py: error: the following arguments are required: --repo-id
```

## Conclusion

I've tried this in a fresh conda env and the result is the same. I think we should remove torch from dependencies and request users to download this manually. I think @NicolasHug bought this up a few times as well.

**Comment by joecummings** [comment]
We no longer use torch through requirements.txt, instead we require users to install pytorch via https://pytorch.org/get-started/locally/
