### ISSUE TITLE
AC does not work w/ LoRA finetunes

### ISSUE THREAD

**Issue by joecummings** [pytorch/torchtune#521]
Env: Python 3.11
Latest commit on main: #515 
Recipe & configs: Both LoRA recipes, no changes to config
Did you run from fresh install and download of model? Yes

Traceback:
```
Traceback (most recent call last):
  File "/home/jrcummings/projects/torchtune/recipes/lora_finetune_distributed.py", line 488, in <module>
    sys.exit(recipe_main())
             ^^^^^^^^^^^^^
  File "/home/jrcummings/projects/torchtune/torchtune/config/_parse.py", line 54, in wrapper
    sys.exit(recipe_main(conf))
             ^^^^^^^^^^^^^^^^^
  File "/home/jrcummings/projects/torchtune/recipes/lora_finetune_distributed.py", line 483, in recipe_main
    recipe.train()
  File "/home/jrcummings/projects/torchtune/recipes/lora_finetune_distributed.py", line 450, in train
    self._grad_scaler.scale(loss).backward()
  File "/home/jrcummings/.conda/envs/torchtune/lib/python3.11/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/jrcummings/.conda/envs/torchtune/lib/python3.11/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

Simply by changing AC: False, the error went away.

**Comment by joecummings** [comment]
With updates, this went away
