### ISSUE TITLE
No ignore_index for DPO Loss

### ISSUE THREAD

**Issue by jxmsML** [pytorch/torchtune#919]
Run into issue with DPO loss training

```
[rank4]: Traceback (most recent call last):
[rank4]:   File "/data/home/jingxu23/src/torchtune_240501/recipes/full_finetune_distributed.py", line 552, in <module>
[rank4]:
[rank4]:   File "/data/home/jingxu23/src/torchtune_240501/torchtune/config/_parse.py", line 50, in wrapper
[rank4]:     sys.exit(recipe_main(conf))
[rank4]:   File "/data/home/jingxu23/src/torchtune_240501/recipes/full_finetune_distributed.py", line 546, in recipe_main
[rank4]:     config.log_config(recipe_name="FullFinetuneRecipeDistributed", cfg=cfg)
[rank4]:   File "/data/home/jingxu23/src/torchtune_240501/recipes/full_finetune_distributed.py", line 209, in setup
[rank4]:
[rank4]:   File "/data/home/jingxu23/src/torchtune_240501/recipes/full_finetune_distributed.py", line 378, in _setup_data
[rank4]:     collate_fn=partial(
[rank4]:   File "/data/home/jingxu23/miniconda/envs/torchtune_240501/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
[rank4]:     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
[rank4]: AttributeError: 'DPOLoss' object has no attribute 'ignore_index'
```

**Comment by ebsmothers** [comment]
Hi @jxmsML, are you looking to perform DPO training? If so I think you may want to use the `lora_dpo_distributed` recipe instead of the `full_finetune_distributed` recipe. The full fine-tune recipe is not set up to run with DPO.

**Comment by ebsmothers** [comment]
Closing this since it seems to be resolved. However, feel free to reopen if you are still seeing issues here.
